(part "NLV32T-181J-EF"
    (packageRef "INDM3225X240N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "810-NLV32T-181J-EF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TDK/NLV32T-181J-EF?qs=u4%252BEJ9urDARpHz3fJZRHLg%3D%3D")
    (property "Manufacturer_Name" "TDK")
    (property "Manufacturer_Part_Number" "NLV32T-181J-EF")
    (property "Description" "TDK - NLV32T-181J-EF - High Frequency Inductor, 180 ?H, NLV32-EF Series, 60 mA, 1210 [3225 Metric], Wirewound, 17 ohm")
    (property "Datasheet_Link" "https://product.tdk.com/system/files/dam/doc/product/inductor/inductor/smd/catalog/inductor_commercial_standard_nlv32-ef_en.pdf")
    (property "symbolName1" "NLV32T-181J-EF")
)
